### ISSUE TITLE
Running convolution.py example results in AttributeError

### ISSUE THREAD

**Issue by viktor-ferenczi** [iskandr/parakeet#28]
Successfully installed parakeet on **Ubuntu 14.04 LTS 64bit + up to date Anaconda**

All parakeet unit tests completed successfully:

```
fviktor@ml:~/dev/parakeet/test$ nosetests --processes=6 .
.........................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 409 tests in 37.595s

OK
```

**numpy version: 1.9.2**

Tried to run convolution.py example, but got exception: 

```
fviktor@ml:~/dev/parakeet/examples$ python convolution.py 
Input [[  2.58042993e-01   5.62971928e-01   3.18518354e-01 ...,  -4.92677614e-01
   -5.33775979e-01  -1.08248866e+00]
 [  4.90764757e-03   1.17602492e+00  -2.87544067e-03 ...,   7.22071302e-01
    3.81995794e-01  -2.45555615e-01]
 [  1.31822646e+00   1.15793986e+00   1.14658108e+00 ...,  -1.12846011e+00
    1.19572064e+00   3.12640182e+00]
 ..., 
 [ -2.06217431e-01  -2.20358510e-03   1.80575683e+00 ...,   6.71510654e-01
    3.18903622e-01   1.30837962e-01]
 [  4.84092250e-01  -3.69639627e-01  -2.79786297e-01 ...,  -1.35688015e+00
   -1.10111849e+00   2.49257160e-01]
 [ -2.35768967e-02  -1.46622324e+00   5.89974521e-02 ...,  -1.23096420e+00
   -3.50698146e-01   6.66309537e-01]]
Convolved output
Traceback (most recent call last):
  File "convolution.py", line 24, in <module>
    print "Convolved output", conv_3x3_trim(x,w)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/frontend/decorators.py", line 27, in __call__
    return run_typed_fn(typed_fn, linear_args, backend_name)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/frontend/run_function.py", line 77, in run_typed_fn
    return c_backend.run(fn, args)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/c_backend/run_function.py", line 13, in run
    fn = lower_to_loops(fn)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 120, in __call__
    return self.apply(fn, run_dependencies)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 153, in apply
    fn = apply_transforms(fn, self.depends_on)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 29, in apply_transforms
    fn = t.apply(fn)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 153, in apply
    fn = apply_transforms(fn, self.depends_on)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 29, in apply_transforms
    fn = t.apply(fn)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 153, in apply
    fn = apply_transforms(fn, self.depends_on)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 29, in apply_transforms
    fn = t.apply(fn)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 153, in apply
    fn = apply_transforms(fn, self.depends_on)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 29, in apply_transforms
    fn = t.apply(fn)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 168, in apply
    transform_history = fn.transform_history)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 36, in apply_transforms
    fn = apply_transforms(fn, cleanup, [], phase_name = "cleanup")
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/phase.py", line 29, in apply_transforms
    fn = t.apply(fn)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/transform.py", line 492, in apply
    pre_fn = self.pre_apply(self.fn)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/transforms/simplify.py", line 52, in pre_apply
    self.mutable_types = ma.visit_fn(fn)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/analysis/mutability_analysis.py", line 79, in visit_fn
    self.visit_block(fn.body)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/analysis/syntax_visitor.py", line 272, in visit_block
    self.visit_stmt(s)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/analysis/syntax_visitor.py", line 343, in visit_stmt
    getattr(self, self._stmt_method_names[c])(stmt)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/analysis/syntax_visitor.py", line 296, in visit_Return
    self.visit_expr(stmt.value)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/analysis/syntax_visitor.py", line 237, in visit_expr
    return method(expr)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/analysis/syntax_visitor.py", line 129, in visit_OuterMap
    self.visit_expr(arg)
  File "/home/fviktor/anaconda/lib/python2.7/site-packages/parakeet-0.24-py2.7.egg/parakeet/analysis/syntax_visitor.py", line 234, in visit_expr
    method = getattr(self, method_name)
AttributeError: 'TypeBasedMutabilityAnalysis' object has no attribute 'visit_NoneType'
```

**Comment by iskandr** [comment]
Hey @viktor-ferenczi, 

I've been working in a different domain since I finished my PhD and don't have time to maintain the project (or, specifically, figure out what's going wrong in this case). I'll mark the project deprecated to not get people's hopes up.

**Comment by jumpingtheshark** [comment]
Can I take it over ?

**Comment by iskandr** [comment]
Ownership passed on to @jumpingtheshark!
